<?php


namespace Adamantine\Adamantine;


use Closure;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\ServiceProvider;

class AdamantineServiceProvider extends ServiceProvider {
    public function boot()
    {
        $this->loadViewsFrom(__DIR__.'/Resources/views', 'adamantine');
        $this->publishes([__DIR__.'/Resources/assets' => public_path()], 'adamantine');
        $this->publishes([__DIR__.'/Config' => base_path('config')], 'adamantine');

        require 'routes.php';
    }

    public function register() {
        $this->commands([
            Commands\DeveloperArea::class
        ]);
    }

    public function booted(Closure $callback)
    {
        parent::booted($callback); // TODO: Change the autogenerated stub
    }

}
